### ISSUE TITLE
I don't understand this Error

### ISSUE THREAD

**Issue by DavidFoden** [DavidFoden/BookLibrary#2]
![image](https://user-images.githubusercontent.com/36032962/46459647-c99a2600-c7b9-11e8-8947-6303dbdc8665.png)

I'm not sure what it means and looking at my code with Stephen it looks right maybe I missed something but I cant see it.

**Comment by christanfoden** [comment]
its to do with your DispatchToProps and I think the only place you are doing this is in `/src/containers/book-list.js` is this correct? 

line 34:

```
function mapDispatchToProps(dispatch) {
  return bindActionCreators({ selectBook: selectBook });
}
```

You pass dispatch in to the function but you don't seem to use it is that correct?

**Comment by DavidFoden** [comment]
Yeah your right it was because of Dispatch I didn't define what "Dispatch" was so therefore it could not load my "onClick" that error came up
Cheers ⛅️

**Comment by christanfoden** [comment]
So just for future reference, the correct code is:

```
function mapDispatchToProps(dispatch) {
  return bindActionCreators({ selectBook: selectBook }, dispatch);
}
```
